# Generated by Django 2.2.7 on 2020-01-18 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_payment_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='company',
        ),
        migrations.AlterField(
            model_name='payment',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='database.Branch'),
        ),
    ]
