# Generated by Django 2.2.7 on 2020-01-18 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_auto_20200118_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='database.Branch'),
        ),
    ]
