# Generated by Django 2.2.7 on 2020-01-19 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_remove_payment_bank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='card_bill_number',
        ),
    ]
