# Generated by Django 2.2.7 on 2020-03-11 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0013_auto_20200311_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorpayment',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vendorpayment',
            name='cheque_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendorpayment',
            name='cheque_number',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendorpayment',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendorpayment',
            name='payment_mode',
            field=models.CharField(choices=[('cash', 'cash'), ('cheque', 'cheque')], default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendorpayment',
            name='received_by',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
