# Generated by Django 2.2.7 on 2020-03-12 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0016_auto_20200312_1302'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendorpayment',
            options={'ordering': ['-payment_status']},
        ),
    ]
