# Generated by Django 2.2.7 on 2020-01-15 16:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_auto_20200115_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='dob',
            field=models.DateField(default=datetime.datetime(2020, 1, 15, 16, 4, 19, 587613, tzinfo=utc)),
        ),
    ]
