# Generated by Django 2.2.7 on 2020-01-15 16:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_auto_20200115_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='dob',
            field=models.DateField(default=datetime.datetime(2020, 1, 15, 16, 17, 15, 660035, tzinfo=utc)),
        ),
    ]
