# Generated by Django 2.2.7 on 2020-01-16 12:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0014_auto_20200116_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='dob',
            field=models.DateField(default=datetime.datetime(2020, 1, 16, 12, 12, 57, 718742, tzinfo=utc)),
        ),
    ]
