# Generated by Django 2.2.7 on 2020-01-17 03:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0017_auto_20200116_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='dob',
            field=models.DateField(default=datetime.datetime(2020, 1, 17, 2, 59, 57, 37100, tzinfo=utc)),
        ),
    ]
