# Generated by Django 2.2.7 on 2020-01-17 12:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0021_auto_20200117_0821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='dob',
            field=models.DateField(default=datetime.datetime(2020, 1, 17, 12, 0, 53, 958756, tzinfo=utc)),
        ),
    ]
