# Generated by Django 2.2.7 on 2020-01-18 05:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0024_auto_20200118_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='dob',
            field=models.DateField(default=datetime.datetime(2020, 1, 18, 5, 33, 0, 68946, tzinfo=utc)),
        ),
    ]
