# Generated by Django 2.2.7 on 2020-01-18 06:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0027_auto_20200118_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='dob',
            field=models.DateField(default=datetime.datetime(2020, 1, 18, 6, 54, 58, 575941, tzinfo=utc)),
        ),
    ]
