# Generated by Django 2.2.7 on 2020-01-18 07:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0030_auto_20200118_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='dob',
            field=models.DateField(default=datetime.datetime(2020, 1, 18, 7, 3, 32, 249657, tzinfo=utc)),
        ),
    ]
