# Generated by Django 2.2.7 on 2020-01-19 09:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0035_auto_20200119_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='dob',
            field=models.DateField(default=datetime.datetime(2020, 1, 19, 9, 13, 43, 760961, tzinfo=utc)),
        ),
    ]
