# Generated by Django 2.2.7 on 2020-01-19 09:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0036_auto_20200119_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='dob',
            field=models.DateField(default=datetime.datetime(2020, 1, 19, 9, 14, 31, 257816, tzinfo=utc)),
        ),
    ]
