# Generated by Django 2.2.7 on 2020-01-19 12:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0037_auto_20200119_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='dob',
            field=models.DateField(default=datetime.datetime(2020, 1, 19, 12, 46, 28, 29092, tzinfo=utc)),
        ),
    ]
