# Generated by Django 2.2.7 on 2020-01-19 12:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0038_auto_20200119_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='dob',
            field=models.DateField(default=datetime.datetime(2020, 1, 19, 12, 49, 55, 492124, tzinfo=utc)),
        ),
    ]
