# Generated by Django 2.2.7 on 2020-01-20 02:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0039_auto_20200119_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='dob',
            field=models.DateField(default=datetime.datetime(2020, 1, 20, 2, 47, 34, 245422, tzinfo=utc)),
        ),
    ]
