# Generated by Django 2.2.7 on 2020-01-20 03:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0042_auto_20200120_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='dob',
            field=models.DateField(default=datetime.datetime(2020, 1, 20, 3, 21, 45, 177593, tzinfo=utc)),
        ),
    ]
