# Generated by Django 2.2.7 on 2020-01-20 07:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0043_auto_20200120_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='dob',
            field=models.DateField(default=datetime.datetime(2020, 1, 20, 7, 11, 34, 458381, tzinfo=utc)),
        ),
    ]
