# Generated by Django 2.2.7 on 2020-01-20 13:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0047_auto_20200120_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='dob',
            field=models.DateField(default=datetime.datetime(2020, 1, 20, 13, 7, 3, 339056, tzinfo=utc)),
        ),
    ]
