# Generated by Django 2.2.7 on 2020-01-21 05:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0048_auto_20200120_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='dob',
            field=models.DateField(default=datetime.datetime(2020, 1, 21, 5, 53, 46, 11935, tzinfo=utc)),
        ),
    ]
