# Generated by Django 2.2.7 on 2020-01-21 09:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0051_auto_20200121_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='dob',
            field=models.DateField(default=datetime.datetime(2020, 1, 21, 9, 53, 16, 392608, tzinfo=utc)),
        ),
    ]
