# Generated by Django 2.2.7 on 2020-01-21 10:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0052_auto_20200121_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='dob',
            field=models.DateField(default=datetime.datetime(2020, 1, 21, 10, 55, 12, 174339, tzinfo=utc)),
        ),
    ]
