# Generated by Django 2.2.7 on 2020-01-21 11:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0055_auto_20200121_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='dob',
            field=models.DateField(default=datetime.date(1996, 1, 1)),
        ),
    ]
