# Generated by Django 2.2.7 on 2020-01-22 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0011_auto_20200120_1334'),
        ('employee', '0056_auto_20200121_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='branchh',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='database.Branch'),
        ),
    ]
