# Generated by Django 2.2.7 on 2020-01-23 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0058_auto_20200123_0927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='active',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='staff',
        ),
    ]
