# Generated by Django 2.2.7 on 2020-01-24 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0060_auto_20200123_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', null=True, verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this site.', null=True, verbose_name='staff status'),
        ),
    ]
