# Generated by Django 2.2.7 on 2020-01-28 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0062_employee_employee_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='branchh',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='database.Branch'),
        ),
    ]
