# Generated by Django 2.2.7 on 2020-01-15 13:03

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('database', '0002_auto_20200115_1301'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_order_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='purchase order number')),
                ('purchase_order_date', models.DateField(default=datetime.datetime(2020, 1, 15, 13, 3, 25, 43456, tzinfo=utc), verbose_name='purchase order date')),
                ('vendor_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='vendor_name')),
                ('shipping_term', models.CharField(blank=True, max_length=100, null=True, verbose_name='shipping term')),
                ('shipping_date', models.DateField(default=datetime.datetime(2020, 1, 15, 13, 3, 25, 43563, tzinfo=utc), verbose_name='shipping date')),
                ('payment_terms', models.CharField(blank=True, max_length=100, null=True, verbose_name='payment terms')),
                ('payment_method', models.CharField(blank=True, max_length=100, null=True, verbose_name='payment method')),
                ('shipping_charge', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='shipping charge')),
                ('additional_discount_percentage', models.PositiveIntegerField(blank=True, null=True, verbose_name='additional discount(%)')),
                ('vat', models.BooleanField(default=True, verbose_name='vat')),
                ('tax', models.BooleanField(default=True, verbose_name='tax')),
                ('final_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('vendor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Vendor', verbose_name='vendor id')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=100, verbose_name='item')),
                ('uom', models.CharField(max_length=100, verbose_name='uom')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='unit price')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='quantity')),
                ('discount', models.PositiveIntegerField(blank=True, null=True, verbose_name='discount(%)')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='amount')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='inventory.PurchaseOrder')),
            ],
        ),
    ]
