# Generated by Django 2.2.7 on 2020-01-26 13:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0014_auto_20200126_1906'),
        ('inventory', '0090_auto_20200126_1841'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(max_length=100, verbose_name='vendor name')),
                ('address', models.TextField(verbose_name='address')),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{7,15}$')], verbose_name='phone number')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('total_paid_amount', models.DecimalField(blank=True, decimal_places=2, help_text='total amount paid by company', max_digits=20, null=True)),
                ('total_credit_amount', models.DecimalField(blank=True, decimal_places=2, help_text='total credit amount of company', max_digits=20, null=True)),
                ('total_purchase_amount', models.DecimalField(blank=True, decimal_places=2, help_text='total purchase amount till date', max_digits=20, null=True)),
                ('credit_limit', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=20, null=True)),
                ('notify_credit_limit', models.CharField(blank=True, choices=[('1', 'notify over limit'), ('2', 'hold over limit')], help_text='notification for credit limits', max_length=100, null=True)),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendor', to='database.Branch')),
            ],
        ),
        migrations.AlterField(
            model_name='billofstock',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.Vendor'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Vendor', verbose_name='vendor'),
        ),
        migrations.CreateModel(
            name='ContactPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{7,15}$')], verbose_name='phone number')),
                ('email', models.EmailField(max_length=254)),
                ('vat_or_pan_number', models.PositiveIntegerField(verbose_name='vat/pan number')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_persons', to='inventory.Vendor')),
            ],
        ),
    ]
