# Generated by Django 2.2.7 on 2020-01-28 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0091_auto_20200126_1906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockcomputation',
            name='sale_quantity',
        ),
    ]
