# Generated by Django 2.2.7 on 2020-01-28 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0093_auto_20200128_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='item',
            field=models.CharField(max_length=100),
        ),
    ]
