# Generated by Django 2.2.7 on 2020-01-28 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0094_auto_20200128_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='threshold_quantity',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
