# Generated by Django 2.2.7 on 2020-01-31 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0096_auto_20200128_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='total_purchase_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='total purchase amount till date', max_digits=20, null=True),
        ),
    ]
