# Generated by Django 2.2.7 on 2020-01-30 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0098_auto_20200129_1330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='purchaseorder_number',
        ),
    ]
