# Generated by Django 2.2.7 on 2020-01-31 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0100_auto_20200130_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='shipping_date',
            field=models.DateField(blank=True, null=True, verbose_name='shipping date'),
        ),
    ]
