# Generated by Django 2.2.7 on 2020-01-31 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0102_auto_20200131_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billofstock',
            name='additional_discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=4, null=True, verbose_name='additional discount(%)'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='additional_discount_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=4, null=True, verbose_name='additional discount(%)'),
        ),
    ]
