# Generated by Django 2.2.7 on 2020-01-31 11:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0103_auto_20200131_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitemcosting',
            name='cost_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
