# Generated by Django 2.2.7 on 2020-02-08 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0105_auto_20200131_1910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitemcosting',
            name='cost_price',
        ),
        migrations.AlterField(
            model_name='item',
            name='item',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
