# Generated by Django 2.2.7 on 2020-02-09 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0106_auto_20200208_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item',
            field=models.CharField(max_length=100),
        ),
    ]
