# Generated by Django 2.2.7 on 2020-02-14 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0107_auto_20200209_1452'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billofstock',
            options={'ordering': ['-created_at']},
        ),
    ]
