# Generated by Django 2.2.7 on 2020-02-14 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0108_auto_20200214_1534'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billofstock',
            options={'ordering': ['created_at']},
        ),
    ]
