# Generated by Django 2.2.7 on 2020-02-14 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0109_auto_20200214_1536'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billofstock',
            options={},
        ),
    ]
