# Generated by Django 2.2.7 on 2020-02-25 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0113_stockcomputation_total_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockcomputation',
            name='total_amount',
        ),
    ]
