# Generated by Django 2.2.7 on 2020-02-25 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0114_remove_stockcomputation_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockcomputation',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
