# Generated by Django 2.2.7 on 2020-02-25 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0115_stockcomputation_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockcomputation',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
