# Generated by Django 2.2.7 on 2020-03-04 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0116_auto_20200225_1916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockcomputation',
            name='total_amount',
        ),
    ]
