# Generated by Django 2.2.7 on 2020-03-04 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0117_remove_stockcomputation_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockcomputation',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
