# Generated by Django 2.2.7 on 2020-03-11 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0119_auto_20200310_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='billofstock',
            name='payment_status',
            field=models.CharField(choices=[('paid', 'paid'), ('unpaid', 'unpaid')], default='unpaid', max_length=100),
        ),
    ]
