# Generated by Django 2.2.7 on 2020-03-12 06:55

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0120_billofstock_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='total_credit_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='total credit amount of company', max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='total_paid_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='total amount paid by company', max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='total_purchase_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='total purchase amount till date', max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
