# Generated by Django 2.2.7 on 2020-03-12 07:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0121_auto_20200312_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='total_credit_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='total credit amount of company', max_digits=20, validators=[django.core.validators.MinValueValidator('0.00')]),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='total_paid_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='total amount paid by company', max_digits=20, validators=[django.core.validators.MinValueValidator('0.00')]),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='total_purchase_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='total purchase amount till date', max_digits=20, validators=[django.core.validators.MinValueValidator('0.00')]),
        ),
    ]
