# Generated by Django 2.2.7 on 2020-01-17 18:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_auto_20200115_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='branch_contact',
            field=models.CharField(max_length=15, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{7,15}$')]),
        ),
        migrations.AddField(
            model_name='branch',
            name='branch_contact_extra',
            field=models.CharField(max_length=15, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{7,15}$')]),
        ),
        migrations.AlterField(
            model_name='branch',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branch', to='database.CompanyDetail'),
        ),
        migrations.DeleteModel(
            name='BranchContact',
        ),
    ]
