# Generated by Django 2.2.7 on 2020-01-18 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_auto_20200118_1100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='company',
        ),
        migrations.RemoveField(
            model_name='floor',
            name='company',
        ),
        migrations.RemoveField(
            model_name='seatingtype',
            name='company',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='company',
        ),
        migrations.AlterField(
            model_name='customer',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='database.Branch'),
        ),
        migrations.AlterField(
            model_name='floor',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='floor', to='database.Branch'),
        ),
        migrations.AlterField(
            model_name='seatingtype',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seatingtype', to='database.Branch'),
        ),
    ]
