# Generated by Django 2.2.7 on 2020-01-18 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_auto_20200118_1133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seatingtype',
            name='branch',
        ),
        migrations.AlterField(
            model_name='branch',
            name='location',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
