# Generated by Django 2.2.7 on 2020-01-20 02:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_auto_20200118_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='branch_contact_extra',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{7,15}$')]),
        ),
    ]
