# Generated by Django 2.2.7 on 2020-01-20 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_auto_20200120_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='contact_person',
            field=models.ManyToManyField(related_name='contact_person', to='database.ContactPerson', verbose_name='contact person'),
        ),
    ]
