# Generated by Django 2.2.7 on 2020-01-20 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0009_auto_20200120_1256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='contact_person',
        ),
        migrations.AddField(
            model_name='contactperson',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_person', to='database.Vendor'),
        ),
    ]
