# Generated by Django 2.2.7 on 2020-01-26 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0013_auto_20200124_1551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='branch',
        ),
        migrations.DeleteModel(
            name='ContactPerson',
        ),
    ]
