# Generated by Django 2.2.7 on 2020-01-26 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0091_auto_20200126_1906'),
        ('database', '0014_auto_20200126_1906'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vendor',
        ),
    ]
