# Generated by Django 2.2.7 on 2020-01-28 09:30

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0015_delete_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydetail',
            name='contact_number',
            field=models.CharField(max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{7,15}$')]),
        ),
        migrations.AlterField(
            model_name='branch',
            name='branch_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='branch',
            name='location',
            field=models.CharField(default='head office', max_length=100, unique=True),
        ),
    ]
