# Generated by Django 2.2.7 on 2020-01-30 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0017_auto_20200129_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floor',
            name='floor_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
