# Generated by Django 2.2.7 on 2020-02-10 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0018_auto_20200130_1324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companydetail',
            name='company_logo',
        ),
    ]
