# Generated by Django 2.2.7 on 2020-02-10 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0019_remove_companydetail_company_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydetail',
            name='company_logo',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
