# Generated by Django 2.2.7 on 2020-01-15 13:01

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('database', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('delivery_status', models.CharField(choices=[('in_progress', 'In Progress'), ('delivered', 'Delivered')], default='in_progress', max_length=20)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Customer')),
                ('delivery_person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Deliveries',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ItemDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{7,15}$')])),
                ('sd', models.DateTimeField(verbose_name='start time')),
                ('ed', models.DateTimeField(verbose_name='end time')),
                ('special_mention', models.TextField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservation_approved', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Customer')),
                ('waiter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UnitOfMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uom', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Seating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seating_number', models.PositiveIntegerField(blank=True, null=True)),
                ('seating_name', models.CharField(max_length=100, null=True)),
                ('capacity', models.PositiveIntegerField(default=0)),
                ('seating_status', models.CharField(choices=[('reserved', 'Reserved'), ('occupied', 'Occupied'), ('available', 'Available')], default='available', max_length=30)),
                ('merge_reference', models.PositiveIntegerField(blank=True, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.Customer')),
                ('floor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seating', to='database.Floor')),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sale.Reservation')),
                ('seating_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='database.SeatingType')),
                ('waiter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seating_waiter', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_order', models.DateField(auto_now_add=True)),
                ('take_away_charge', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('order_type', models.CharField(choices=[('take_away', 'take away'), ('dine_in', 'dine in'), ('delivery', 'delivery')], default='dine_in', max_length=15)),
                ('order_status', models.CharField(choices=[('ordered', 'Ordered'), ('in_progress', 'In progress'), ('ready', 'Ready'), ('served', 'Served'), ('revised', 'Revised')], default='ordered', max_length=30)),
                ('delivery_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('final_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='database.CompanyDetail')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='database.Customer')),
                ('delivery', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='sale.Delivery')),
                ('seating', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='sale.Seating')),
            ],
        ),
        migrations.CreateModel(
            name='ModifierItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modifier_name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('item_type', models.CharField(choices=[('veg', 'Veg'), ('non_veg', 'Non-veg'), ('undefined', 'Undefined')], default='veg', max_length=30)),
                ('item_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('item_description', models.TextField(blank=True, null=True)),
                ('uom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sale.UnitOfMaterial')),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('item_type', models.CharField(choices=[('veg', 'Veg'), ('non_veg', 'Non-veg'), ('undefined', 'Undefined')], default='undefined', max_length=30)),
                ('item_image', models.ImageField(null=True, upload_to='')),
                ('item_description', models.TextField(blank=True, null=True)),
                ('size', models.CharField(blank=True, max_length=100, null=True)),
                ('packing_charge', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('reward_point', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sale.Category')),
                ('modifier_item', models.ManyToManyField(blank=True, null=True, to='sale.ModifierItem')),
                ('uom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sale.UnitOfMaterial')),
            ],
        ),
        migrations.CreateModel(
            name='Itemline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('free', models.BooleanField(default=False)),
                ('description', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sale.ItemDescription')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sale.MenuItem')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itemline', to='sale.Order')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.PositiveIntegerField(null=True, unique=True)),
                ('customer_name', models.CharField(max_length=100, null=True)),
                ('bill_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('misc_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('service_charge', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Service charge(%)')),
                ('service_charge_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('vat', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='VAT(%)')),
                ('vat_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount_from_reward', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('additional_discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('final_bill_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('return_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_mode', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('Credit', 'Credit')], default='cash', max_length=50)),
                ('card_number', models.PositiveIntegerField(blank=True, null=True)),
                ('card_bill_number', models.PositiveIntegerField(blank=True, null=True)),
                ('invoice_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid')], default='unpaid', max_length=20)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sale.Bank')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='database.CompanyDetail')),
                ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='sale.Order')),
                ('seating', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='sale.Seating')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sale.Department'),
        ),
    ]
