# Generated by Django 2.2.7 on 2020-01-16 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0003_seating_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='can_be_free',
            field=models.BooleanField(default=False),
        ),
    ]
