# Generated by Django 2.2.7 on 2020-01-16 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0005_auto_20200116_0755'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ItemDescription',
            new_name='ItemInstruction',
        ),
        migrations.RenameField(
            model_name='itemline',
            old_name='description',
            new_name='instruction',
        ),
    ]
