# Generated by Django 2.2.7 on 2020-01-16 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0006_auto_20200116_0809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemline',
            name='instruction',
        ),
        migrations.AddField(
            model_name='order',
            name='instruction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='sale.ItemInstruction'),
        ),
    ]
