# Generated by Django 2.2.7 on 2020-01-16 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0008_auto_20200116_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('ordered', 'Ordered'), ('in_progress', 'In progress'), ('ready', 'Ready'), ('served', 'Served'), ('revised', 'Revised')], default='ordered', max_length=30, null=True),
        ),
    ]
