# Generated by Django 2.2.7 on 2020-01-17 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0010_order_waiter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='instruction',
            field=models.TextField(blank=True, null=True),
        ),
    ]
