# Generated by Django 2.2.7 on 2020-01-17 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0011_auto_20200117_0801'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ItemInstruction',
        ),
    ]
