# Generated by Django 2.2.7 on 2020-01-18 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0016_auto_20200118_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='sale.Department'),
        ),
        migrations.AlterField(
            model_name='department',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='department', to='database.Branch'),
        ),
        migrations.AlterField(
            model_name='seating',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seating', to='database.Branch'),
        ),
    ]
