# Generated by Django 2.2.7 on 2020-01-19 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_remove_payment_order'),
        ('sale', '0020_auto_20200119_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='payment.Payment'),
        ),
    ]
