# Generated by Django 2.2.7 on 2020-01-21 07:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0022_auto_20200120_0833'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='bill_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
