# Generated by Django 2.2.7 on 2020-01-21 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0026_invoice_customer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='available_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
