# Generated by Django 2.2.7 on 2020-01-21 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0027_invoice_available_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='modifier_item',
            field=models.ManyToManyField(blank=True, to='sale.ModifierItem'),
        ),
    ]
