# Generated by Django 2.2.7 on 2020-01-21 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0028_auto_20200121_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='pay_from_debit',
            field=models.BooleanField(default=False),
        ),
    ]
