# Generated by Django 2.2.7 on 2020-01-22 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0030_auto_20200122_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
