# Generated by Django 2.2.7 on 2020-01-22 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0011_auto_20200120_1334'),
        ('sale', '0031_auto_20200122_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationtable',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='database.Branch'),
        ),
        migrations.AlterField(
            model_name='notificationtable',
            name='message',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
