# Generated by Django 2.2.7 on 2020-01-22 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0032_auto_20200122_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationtable',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Branch'),
        ),
        migrations.AlterField(
            model_name='notificationtable',
            name='message',
            field=models.CharField(max_length=255),
        ),
    ]
