# Generated by Django 2.2.7 on 2020-01-22 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0033_auto_20200122_2015'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificationtable',
            options={},
        ),
    ]
