# Generated by Django 2.2.7 on 2020-01-24 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0013_auto_20200124_1551'),
        ('sale', '0036_auto_20200123_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitofmaterial',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='database.CompanyDetail'),
        ),
    ]
