# Generated by Django 2.2.7 on 2020-01-26 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0038_auto_20200124_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid'), ('canceled', 'Canceled')], default='unpaid', max_length=20),
        ),
    ]
