# Generated by Django 2.2.7 on 2020-01-26 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0039_auto_20200126_1232'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='remarks',
            new_name='remark',
        ),
    ]
