# Generated by Django 2.2.7 on 2020-02-17 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0042_auto_20200216_1251'),
        ('sale', '0042_auto_20200214_1455'),
    ]

    operations = [
    ]
