# Generated by Django 2.2.7 on 2020-03-03 04:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0044_invoice_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 3, 3, 10, 27, 23, 533463), null=True),
        ),
    ]
