# Generated by Django 2.2.7 on 2020-03-04 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0048_auto_20200303_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='created_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
